# Generated by Django 3.2.9 on 2021-11-19 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0002_cropdetails_farmer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoShip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.IntegerField(null=True)),
                ('CargoShip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Document.cargoship')),
            ],
        ),
    ]
